### ISSUE TITLE
Compatibility with Python 3.12+???

### ISSUE THREAD

**Issue by hmaarrfk** [inaccel/numpy-allocator#3]
I'm having trouble getting compilation to work on 3.12 and 3.13.

something doesn't seem to be able to find `PyDataMem_SetHandler` but I'm confused why.... help appreciated.

https://github.com/conda-forge/numpy-allocator-feedstock/pull/10

**Comment by leofang** [comment]
We're hitting the same issue with Python 3.12, no pre-built wheel exists and building it locally leads to the following error
<details>
<summary>error output</summary>
```
$ pip install -v numpy_allocator
Using pip 24.2 from /local/home/leof/miniforge3/envs/cupy_cuda125_dev/lib/python3.12/site-packages/pip (python 3.12)
Collecting numpy_allocator
  Using cached numpy-allocator-1.2.0.tar.gz (10 kB)
  Running command pip subprocess to install build dependencies
  Using pip 24.2 from /local/home/leof/miniforge3/envs/cupy_cuda125_dev/lib/python3.12/site-packages/pip (python 3.12)
    Link requires a different Python (3.12.5 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/3a/be/650f9c091ef71cb01d735775d554e068752d3ff63d7943b26316dc401749/numpy-1.21.2.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
    Link requires a different Python (3.12.5 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/5f/d6/ad58ded26556eaeaa8c971e08b6466f17c4ac4d786cd3d800e26ce59cc01/numpy-1.21.3.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
    Link requires a different Python (3.12.5 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/fb/48/b0708ebd7718a8933f0d3937513ef8ef2f4f04529f1f66ca86d873043921/numpy-1.21.4.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
    Link requires a different Python (3.12.5 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/c2/a8/a924a09492bdfee8c2ec3094d0a13f2799800b4fdc9c890738aeeb12c72e/numpy-1.21.5.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
    Link requires a different Python (3.12.5 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/45/b7/de7b8e67f2232c26af57c205aaad29fe17754f793404f59c8a730c7a191a/numpy-1.21.6.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
  Collecting numpy==1.22.0
    Using cached numpy-1.22.0.zip (11.3 MB)
    Installing build dependencies: started
    Running command pip subprocess to install build dependencies
    Using pip 24.2 from /local/home/leof/miniforge3/envs/cupy_cuda125_dev/lib/python3.12/site-packages/pip (python 3.12)
    Ignoring packaging: markers 'platform_machine == "arm64"' don't match your environment
    Collecting setuptools==59.2.0
      Obtaining dependency information for setuptools==59.2.0 from https://files.pythonhosted.org/packages/18/ad/ec41343a49a0371ea40daf37b1ba2c11333cdd121cb378161635d14b9750/setuptools-59.2.0-py3-none-any.whl.metadata
      Using cached setuptools-59.2.0-py3-none-any.whl.metadata (5.0 kB)
    Collecting wheel==0.37.0
      Obtaining dependency information for wheel==0.37.0 from https://files.pythonhosted.org/packages/04/80/cad93b40262f5d09f6de82adbee452fd43cdff60830b56a74c5930f7e277/wheel-0.37.0-py2.py3-none-any.whl.metadata
      Using cached wheel-0.37.0-py2.py3-none-any.whl.metadata (2.3 kB)
    Collecting Cython<3.0,>=0.29.24
      Obtaining dependency information for Cython<3.0,>=0.29.24 from https://files.pythonhosted.org/packages/c9/aa/99a0eac01136c0c75feb3210d107c49f93d49d5cb97f19e99318b9ecefdd/Cython-0.29.37-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata
      Using cached Cython-0.29.37-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata (3.1 kB)
    Using cached setuptools-59.2.0-py3-none-any.whl (952 kB)
    Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
    Using cached Cython-0.29.37-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (2.0 MB)
    Installing collected packages: wheel, setuptools, Cython
      Creating /tmp/pip-build-env-8r1xgf_f/overlay/bin
      changing mode of /tmp/pip-build-env-8r1xgf_f/overlay/bin/wheel to 755
      changing mode of /tmp/pip-build-env-8r1xgf_f/overlay/bin/cygdb to 755
      changing mode of /tmp/pip-build-env-8r1xgf_f/overlay/bin/cython to 755
      changing mode of /tmp/pip-build-env-8r1xgf_f/overlay/bin/cythonize to 755
    Successfully installed Cython-0.29.37 setuptools-59.2.0 wheel-0.37.0
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Running command Getting requirements to build wheel
    Traceback (most recent call last):
      File "/local/home/leof/miniforge3/envs/cupy_cuda125_dev/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
        main()
      File "/local/home/leof/miniforge3/envs/cupy_cuda125_dev/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/local/home/leof/miniforge3/envs/cupy_cuda125_dev/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
        backend = _build_backend()
                  ^^^^^^^^^^^^^^^^
      File "/local/home/leof/miniforge3/envs/cupy_cuda125_dev/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
        obj = import_module(mod_path)
              ^^^^^^^^^^^^^^^^^^^^^^^
      File "/local/home/leof/miniforge3/envs/cupy_cuda125_dev/lib/python3.12/importlib/__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/tmp/pip-build-env-8r1xgf_f/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
        import setuptools.version
      File "/tmp/pip-build-env-8r1xgf_f/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/tmp/pip-build-env-8r1xgf_f/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
        register_finder(pkgutil.ImpImporter, find_on_path)
                        ^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /local/home/leof/miniforge3/envs/cupy_cuda125_dev/bin/python3.12 /local/home/leof/miniforge3/envs/cupy_cuda125_dev/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpk5nfyp1t
    cwd: /tmp/pip-install-ptj2qguq/numpy_eec295f6d6a646e5a3f5620290280778
    Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /local/home/leof/miniforge3/envs/cupy_cuda125_dev/bin/python3.12 /local/home/leof/miniforge3/envs/cupy_cuda125_dev/lib/python3.12/site-packages/pip/__pip-runner__.py install --ignore-installed --no-user --prefix /tmp/pip-build-env-x8_65z3c/overlay --no-warn-script-location --disable-pip-version-check -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- numpy==1.22.0 setuptools setuptools_scm wheel
  cwd: [inherit]
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
</details>

**Comment by eliaskoromilas** [comment]
I think this is not related to the Python version, but to NumPy version. https://github.com/inaccel/numpy-allocator/issues/4

**Comment by leofang** [comment]
Glad we got everything fixed at once!
